### ISSUE TITLE
Game crash (level 27, easy)

### ISSUE THREAD

**Issue by lg2011** [stransky/berusky#11]
At level 27 in the easy track, in the configuration of the attached screenshot, if I go down with green ladybug then the game crashes.

![Berusky_468](https://user-images.githubusercontent.com/1038713/85944050-5264d800-b934-11ea-96d3-fbc9b6f6d7d3.png)

Thanks for this incredibly addictive game !

**Comment by stransky** [comment]
I'll look at it, Thanks.

**Comment by stransky** [comment]
Yes, I can reproduce it.

**Comment by lg2011** [comment]
Thanks Martin for trying. I now understand that the crash may result from an uncommon situation and that it was not the good way to solve the level...

**Comment by stransky** [comment]
The fix is on the way, I just need to rebuild the package.
