### ISSUE TITLE
Any hint for first impossible level??

### ISSUE THREAD

**Issue by BarbzYHOOL** [stransky/berusky#13]
I wonder if it's worth trying to think about the solution or if it's just a waste of time, like something totally random such as "make 854 steps, turn around, press QTAG and then it opens the path"

Or if it's just impossible and requires cheating

@stransky

**Comment by stransky** [comment]
Yes, it's really impossible as the name says :D As well as the rest in the section...

**Comment by BarbzYHOOL** [comment]
lol ok
