### ISSUE TITLE
Tag version 1.7.1

### ISSUE THREAD

**Issue by akien-mga** [stransky/berusky#4]
The website has a 1.7.1 tarball but there is no corresponding tag in this repo: http://anakreon.cz/?q=node/1

It's not super important, but it would allow tracking the proper latest release here: https://release-monitoring.org/project/8537/

**Comment by akien-mga** [comment]
Pretty ping :)

**Comment by apoleon** [comment]
Yes. Please tag the latest 1.7.1 release and replace the 1.7 tarball on http://www.anakreon.cz/?q=node/1 with version 1.7.1. Thank you.

**Comment by akien-mga** [comment]
Bump @stransky.

**Comment by greno4ka** [comment]
Ping! Are you alive?

**Comment by akien-mga** [comment]
@stransky Still relevant

**Comment by stransky** [comment]
I'll tag that, Thanks.
